### ISSUE TITLE
Create team instead using group as the team

### ISSUE THREAD

**Issue by RaiBnod** [NubeIO/rubix-os#12]
### Tasks to do:

- [x] Create a team model and have CURD operations
- [x] CURD operations of members list inside the team
- [x] CURD operations of views list inside the team
- [x] Remove additional fields & relationships with members of groups which is made for teams
- [x] Have the permission-levels on members (read, write)
