### ISSUE TITLE
Clone edge copies

### ISSUE THREAD

**Issue by RaiBnod** [NubeIO/rubix-os#23]
Parent ticket: [#987](https://github.com/NubeIO/flow-framework/issues/987)
Ongoing task: https://github.com/NubeIO/rubix-os/pull/22

### Issue

- As we are going to remove the `flow_networks` and all those things, we will have an issue with syncing
   -  `edge histories to server history table` (plugin `history`)
    - `server history to Postgres` (plugin `postgres`)

we need to keep fetching those details from edges, which is very ineffective in terms of processing and high data usage.

### Solution

- Keep clones of those edge devices `networks/devices/points` in the cloud
- For a particular host (there will be a sync button on UI)

### Tasks to do:

- [ ] Clones of edge `networks/devices/points` --include `tags` and `meta-tags`
	- bulk operation delete and insert
- [ ] For network: `network.name` & `network.global_uuid` (nullable) should be the `unique constraint`
	- `global_uuid` will be filled only when it's created from the sync option
	- existing GET point by `network.name/device.name/point.name` will have an additional filter where `global_uuid != NULL`, similar to getting devices and networks from the names
- [ ] Additional fields:
    - `source_plugin_name`
    - `source_uuid` in all `networks/devices/points` (we can't have the older `uuid` they can conflict since we are using snapshots)
- [ ] Hide list of `GET: networks` by default
	- `?show_clone_networks=true` (by default `false`)
